// <auto-generated />
using System;
using Api_Academica.DataAccess.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Api_Academica.DataAccess.Migrations
{
    [DbContext(typeof(AcademicDBContext))]
    [Migration("20260530213553_Cambios")]
    partial class Cambios
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Api_Academica.Domain.Entities.Asignatura", b =>
                {
                    b.Property<int>("AsignaturaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AsignaturaId"));

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("Creditos")
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<int>("PlanId")
                        .HasColumnType("int");

                    b.Property<int>("SemestreRecomendado")
                        .HasColumnType("int");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("AsignaturaId");

                    b.HasIndex("PlanId", "Codigo")
                        .IsUnique();

                    b.ToTable("Asignaturas");
                });

            modelBuilder.Entity("Api_Academica.Domain.Entities.Estudiante", b =>
                {
                    b.Property<int>("EstudianteId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EstudianteId"));

                    b.Property<string>("Apellidos")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("CodigoEstudiantil")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("CorreoInstitucional")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<int>("Estado")
                        .HasMaxLength(20)
                        .HasColumnType("int");

                    b.Property<DateOnly>("FechaIngreso")
                        .HasColumnType("date");

                    b.Property<string>("Nombres")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("NumeroDocumento")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<int>("ProgramaId")
                        .HasColumnType("int");

                    b.Property<string>("Telefono")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("TipoDocumento")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.HasKey("EstudianteId");

                    b.HasIndex("CodigoEstudiantil")
                        .IsUnique();

                    b.HasIndex("CorreoInstitucional")
                        .IsUnique();

                    b.HasIndex("NumeroDocumento")
                        .IsUnique();

                    b.HasIndex("ProgramaId");

                    b.ToTable("Estudiantes");
                });

            modelBuilder.Entity("Api_Academica.Domain.Entities.Facultad", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("Estado")
                        .HasMaxLength(20)
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.HasKey("Id");

                    b.ToTable("Facultades");
                });

            modelBuilder.Entity("Api_Academica.Domain.Entities.HistorialAcademico", b =>
                {
                    b.Property<int>("HistorialId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("HistorialId"));

                    b.Property<int>("AsignaturaId")
                        .HasColumnType("int");

                    b.Property<int>("CreditosAprobados")
                        .HasColumnType("int");

                    b.Property<int>("Estado")
                        .HasColumnType("int");

                    b.Property<int>("EstudianteId")
                        .HasColumnType("int");

                    b.Property<decimal>("NotaFinal")
                        .HasColumnType("decimal(3,2)");

                    b.Property<int>("PeriodoId")
                        .HasColumnType("int");

                    b.HasKey("HistorialId");

                    b.HasIndex("AsignaturaId");

                    b.HasIndex("PeriodoId");

                    b.HasIndex("EstudianteId", "AsignaturaId", "PeriodoId")
                        .IsUnique();

                    b.ToTable("HistorialAcademicos");
                });

            modelBuilder.Entity("Api_Academica.Domain.Entities.Matricula", b =>
                {
                    b.Property<int>("MatriculaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MatriculaId"));

                    b.Property<int>("Estado")
                        .HasMaxLength(20)
                        .HasColumnType("int");

                    b.Property<int>("EstudianteId")
                        .HasColumnType("int");

                    b.Property<DateOnly>("FechaMatricula")
                        .HasColumnType("date");

                    b.Property<int>("PeriodoId")
                        .HasColumnType("int");

                    b.HasKey("MatriculaId");

                    b.HasIndex("PeriodoId");

                    b.HasIndex("EstudianteId", "PeriodoId")
                        .IsUnique();

                    b.ToTable("Matriculas");
                });

            modelBuilder.Entity("Api_Academica.Domain.Entities.PeriodoAcademico", b =>
                {
                    b.Property<int>("PeriodoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PeriodoId"));

                    b.Property<int>("Anio")
                        .HasColumnType("int");

                    b.Property<int>("Estado")
                        .HasMaxLength(20)
                        .HasColumnType("int");

                    b.Property<DateOnly>("FechaFin")
                        .HasColumnType("date");

                    b.Property<DateOnly>("FechaInicio")
                        .HasColumnType("date");

                    b.Property<int>("Semestre")
                        .HasColumnType("int");

                    b.HasKey("PeriodoId");

                    b.HasIndex("Anio", "Semestre")
                        .IsUnique();

                    b.ToTable("PeriodosAcademicos");
                });

            modelBuilder.Entity("Api_Academica.Domain.Entities.PlanEstudio", b =>
                {
                    b.Property<int>("PlanId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PlanId"));

                    b.Property<int>("Estado")
                        .HasMaxLength(20)
                        .HasColumnType("int");

                    b.Property<int>("ProgramaId")
                        .HasColumnType("int");

                    b.Property<string>("Version")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("PlanId");

                    b.HasIndex("ProgramaId", "Version")
                        .IsUnique();

                    b.ToTable("PlanesEstudio");
                });

            modelBuilder.Entity("Api_Academica.Domain.Entities.Programa", b =>
                {
                    b.Property<int>("ProgramaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProgramaId"));

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("CreditosTotales")
                        .HasColumnType("int");

                    b.Property<int>("FacultadId")
                        .HasColumnType("int");

                    b.Property<string>("Nivel")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<int>("Semestres")
                        .HasColumnType("int");

                    b.HasKey("ProgramaId");

                    b.HasIndex("Codigo")
                        .IsUnique();

                    b.HasIndex("FacultadId");

                    b.ToTable("Programas");
                });

            modelBuilder.Entity("Api_Academica.Domain.Entities.Asignatura", b =>
                {
                    b.HasOne("Api_Academica.Domain.Entities.PlanEstudio", "PlanEstudio")
                        .WithMany("Asignaturas")
                        .HasForeignKey("PlanId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("PlanEstudio");
                });

            modelBuilder.Entity("Api_Academica.Domain.Entities.Estudiante", b =>
                {
                    b.HasOne("Api_Academica.Domain.Entities.Programa", "Programa")
                        .WithMany("Estudiantes")
                        .HasForeignKey("ProgramaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Programa");
                });

            modelBuilder.Entity("Api_Academica.Domain.Entities.HistorialAcademico", b =>
                {
                    b.HasOne("Api_Academica.Domain.Entities.Asignatura", "Asignatura")
                        .WithMany("HistorialAcademicos")
                        .HasForeignKey("AsignaturaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Api_Academica.Domain.Entities.Estudiante", "Estudiante")
                        .WithMany("HistorialAcademicos")
                        .HasForeignKey("EstudianteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Api_Academica.Domain.Entities.PeriodoAcademico", "PeriodoAcademico")
                        .WithMany("HistorialAcademicos")
                        .HasForeignKey("PeriodoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Asignatura");

                    b.Navigation("Estudiante");

                    b.Navigation("PeriodoAcademico");
                });

            modelBuilder.Entity("Api_Academica.Domain.Entities.Matricula", b =>
                {
                    b.HasOne("Api_Academica.Domain.Entities.Estudiante", "Estudiante")
                        .WithMany("Matriculas")
                        .HasForeignKey("EstudianteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Api_Academica.Domain.Entities.PeriodoAcademico", "Periodo")
                        .WithMany("Matriculas")
                        .HasForeignKey("PeriodoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Estudiante");

                    b.Navigation("Periodo");
                });

            modelBuilder.Entity("Api_Academica.Domain.Entities.PlanEstudio", b =>
                {
                    b.HasOne("Api_Academica.Domain.Entities.Programa", "Programa")
                        .WithMany("PlanesEstudio")
                        .HasForeignKey("ProgramaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Programa");
                });

            modelBuilder.Entity("Api_Academica.Domain.Entities.Programa", b =>
                {
                    b.HasOne("Api_Academica.Domain.Entities.Facultad", "Facultad")
                        .WithMany("Programas")
                        .HasForeignKey("FacultadId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Facultad");
                });

            modelBuilder.Entity("Api_Academica.Domain.Entities.Asignatura", b =>
                {
                    b.Navigation("HistorialAcademicos");
                });

            modelBuilder.Entity("Api_Academica.Domain.Entities.Estudiante", b =>
                {
                    b.Navigation("HistorialAcademicos");

                    b.Navigation("Matriculas");
                });

            modelBuilder.Entity("Api_Academica.Domain.Entities.Facultad", b =>
                {
                    b.Navigation("Programas");
                });

            modelBuilder.Entity("Api_Academica.Domain.Entities.PeriodoAcademico", b =>
                {
                    b.Navigation("HistorialAcademicos");

                    b.Navigation("Matriculas");
                });

            modelBuilder.Entity("Api_Academica.Domain.Entities.PlanEstudio", b =>
                {
                    b.Navigation("Asignaturas");
                });

            modelBuilder.Entity("Api_Academica.Domain.Entities.Programa", b =>
                {
                    b.Navigation("Estudiantes");

                    b.Navigation("PlanesEstudio");
                });
#pragma warning restore 612, 618
        }
    }
}
